[package]
name = "sparsemat"
version = "0.2.0"
authors = ["lostincode"]
edition = "2018"
keywords = ["sparse", "matrix"]
description = "A simple sparse matrix library"
license = "MIT"
repository ="https://github.com/lostinc0de/sparsemat.git"

[dependencies]
